<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAuditsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('audits', function (Blueprint $table) {
            $table->char('id', 36);
            $table->string('type', 255);
            $table->unsignedInteger('auditable_id');
            $table->string('auditable_type', 255);
            $table->text('old')->nullable();
            $table->text('new')->nullable();
            $table->string('user_id', 255)->nullable();
            $table->string('route', 255)->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->timestamp('created_at')->default('CURRENT_TIMESTAMP');

            $table->primary('id');
            $table->index(['auditable_id', 'auditable_type'], 'audits_auditable_id_auditable_type_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('audits');
    }
}
