<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMenuItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('menu_items', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('menu_id')->nullable();
            $table->string('title', 255);
            $table->string('url', 255);
            $table->string('target', 255)->default('_self');
            $table->string('icon_class', 255)->nullable();
            $table->string('color', 255)->nullable();
            $table->integer('parent_id')->nullable();
            $table->integer('order');
            $table->nullableTimestamps();

            

            $table->foreign('menu_id', 'menu_items_menu_id_foreign')->references('id')->on('menus')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('menu_items');
    }
}
