<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateIdeasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ideas', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 250)->nullable();
            $table->string('slug', 250)->nullable();
            $table->unsignedInteger('author_id')->nullable();
            $table->text('body')->nullable();
            $table->integer('viewed_count')->nullable();
            $table->integer('loved_count')->nullable();
            $table->timestamp('moderate_at')->nullable();
            $table->tinyInteger('status')->nullable();
            $table->nullableTimestamps();

            $table->index('author_id', 'author_id');

            $table->foreign('author_id', 'ideas_ibfk_1')->references('id')->on('users')->onDelete('RESTRICT
')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ideas');
    }
}
