<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDataRowsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('data_rows', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('data_type_id');
            $table->string('field', 255);
            $table->string('type', 255);
            $table->string('display_name', 255);
            $table->tinyInteger('required');
            $table->tinyInteger('browse')->default(1);
            $table->tinyInteger('read')->default(1);
            $table->tinyInteger('edit')->default(1);
            $table->tinyInteger('add')->default(1);
            $table->tinyInteger('delete')->default(1);
            $table->text('details')->nullable();

            

            $table->foreign('data_type_id', 'data_rows_data_type_id_foreign')->references('id')->on('data_types')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('data_rows');
    }
}
