<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMediablesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('mediables', function (Blueprint $table) {
            $table->unsignedInteger('media_id');
            $table->string('mediable_type', 255);
            $table->unsignedInteger('mediable_id');
            $table->string('tag', 255);
            $table->unsignedInteger('order');

            $table->primary(['media_id', 'mediable_type', 'mediable_id', 'tag']);
            $table->index(['mediable_id', 'mediable_type'], 'mediables_mediable_id_mediable_type_index');
            $table->index('tag', 'mediables_tag_index');
            $table->index('order', 'mediables_order_index');

            $table->foreign('media_id', 'mediables_media_id_foreign')->references('id')->on('media')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('mediables');
    }
}
