<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAttacherImagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('attacher_images', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('owner_id');
            $table->string('owner_type', 255);
            $table->string('file_extension', 255);
            $table->string('file_name', 255)->nullable();
            $table->unsignedSmallInteger('file_size')->nullable();
            $table->string('mime_type', 255)->nullable();
            $table->nullableTimestamps();

            $table->index('owner_id', 'attacher_images_owner_id_index');
            $table->index('owner_type', 'attacher_images_owner_type_index');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('attacher_images');
    }
}
